config/routes.rb
Rails.application.routes.draw do
  root to: 'words#home'

  get '/:wd' => 'words#home'
  post 'words/search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :word
  has_many :definitions
end

app/models/definition.rb
class Definition < ApplicationRecord
  belongs_to :category
  has_many :examples
end

app/models/example.rb
class Example < ApplicationRecord
  belongs_to :definition
end

app/models/search.rb
class Search
  include HTTParty

  base_uri Rails.application.secrets.dictionary_base_uri
  headers 'app_id' => Rails.application.secrets.dictionary_app_id
  headers 'app_key' => Rails.application.secrets.dictionary_app_key

  def search(text)
    response = self.class.get("/api/v1/entries/en/#{text}", {})

    if response.success?
      txt = response['results'][0]['word']
      word_obj = Word.new
      word_obj.txt = txt

      categories = Array.new

      response['results'][0]['lexicalEntries'].each do |lex_entry|

        definitions = Array.new

        lex_entry['entries'].each do |entry|
          entry['senses'].each do |sense|

            examples = Array.new

            if ! sense['examples'].blank?
              sense['examples'].each do |example|
                example_value = example['text']

                example_obj = Example.new
                example_obj.example = example_value
                examples.push(example_obj)
              end
            end

            if ! sense['definitions'].blank?
              definition_value = sense['definitions'].join("; ")

              definition_obj = Definition.new
              definition_obj.definition = definition_value
              definition_obj.examples = examples

              definitions.push(definition_obj)
            end
          end
        end

        category_value = lex_entry['lexicalCategory']
        category_obj = Category.new
        category_obj.category = category_value
        category_obj.definitions = definitions

        categories.push(category_obj)
      end

      word_obj.categories = categories

      word_obj
    else
      case response.code
        when 404
          error_message = "No information available for '#{text}'."
        when 400
          error_message = "The request was invalid or cannot be otherwise served."
        when 403
          error_message = "The request failed due to invalid credentials. Please contact the administrator."
        else
          error_message = "Something is broken. Please contact us to fix the error."
      end

      raise error_message
    end
  end
end

app/models/word.rb
class Word < ApplicationRecord
  has_many :categories
  validates :txt, presence: true, allow_blank: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def home
    if params[:wd].blank?
      @word = Word.new
    else
      if Word.exists?(:txt => params[:wd])
        @word = Word.find_by_txt(params[:wd])
      else
        if ! search_and_save(params[:wd])
          respond_to do |format|
            format.html { redirect_to root_path}
          end
        end
      end
    end
  end

  def search
    @word = Word.new(word_params)

    if @word.valid?
      if Word.exists?(:txt => @word.txt)
        respond_to do |format|
          format.html { redirect_to :action => "home", :wd => @word.txt}
        end
      else
        if search_and_save(@word.txt)
          respond_to do |format|
            format.html { redirect_to :action => "home", :wd => @word.txt}
          end
        else
          respond_to do |format|
            format.html { redirect_to root_path}
          end
        end
      end
    else
      respond_to do |format|
        format.html {render :home}
      end
    end
  end

  private
    def word_params
      params.require(:word).permit(:txt)
    end

    def search_and_save(text)
      begin
        search = Search.new
        @word = search.search(text)
        save_word(@word)
        return true
      rescue => error
        flash[:notice] = error.message
        return false
      end
    end

    def save_word(word)
      if Word.all.length >= 5
        Word.first.delete
      end

      word.save
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dictionary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/words/_form.html.erb
<%= form_with(url: words_search_path, local: true) do |form| %>
  <div class="search">
    <%= form.text_field "word[txt]", value: word.txt %>
    <%= form.submit("Search") %>

    <% if word.errors.any? %>
        <div>
          <ul>
            <% word.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
  </div>
<% end %>

app/views/words/home.html.erb
<h1>Dictionary Search</h1>

<%= render 'form', word: @word %>

<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>

<div class="section main">
  <% if ! @word.new_record? %>
      <h3>Definition for '<%= @word.txt %>'</h3>

      <ul>
        <% @word.categories.each do |category| %>
            <li>
              Category: <%= category.category %>

              <br /> Definitions
              <ol>
                <% category.definitions.each do |definition| %>
                    <li>
                      <%= definition.definition %>

                      <% if ! definition.examples.blank? %>
                          <br /> Examples
                          <ul>
                            <% definition.examples.each do |example| %>
                                <li><%= example.example %></li>
                            <% end %>
                          </ul>
                      <% end %>
                    </li>
                <% end %>
              </ol>
            </li>
        <% end %>
      </ul>
  <% end %>
  <br/>
</div>
<div class="section side">
  <table>
    <thead>
      <tr>
        <th>Recently searched words</th>
      </tr>
    </thead>
    <tbody>
      <% Word.order("created_at DESC").each do |word| %>
        <tr>
          <td><%= link_to word.txt, :action => "home", :wd => word.txt %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>